/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_keymagic_KeyMagicEngine */

#ifndef _Included_com_keymagic_KeyMagicEngine
#define _Included_com_keymagic_KeyMagicEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_keymagic_KeyMagicEngine
 * Method:    initialise
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_keymagic_KeyMagicEngine_initialise
  (JNIEnv *, jobject);

/*
 * Class:     com_keymagic_KeyMagicEngine
 * Method:    loadKeyboardFile
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_keymagic_KeyMagicEngine_loadKeyboardFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_keymagic_KeyMagicEngine
 * Method:    getKeyState
 * Signature: (I)S
 */
JNIEXPORT jshort JNICALL Java_com_keymagic_KeyMagicEngine_getKeyState
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_keymagic_KeyMagicEngine
 * Method:    setKeyState
 * Signature: (IS)V
 */
JNIEXPORT void JNICALL Java_com_keymagic_KeyMagicEngine_setKeyState
  (JNIEnv *, jobject, jint, jshort);

/*
 * Class:     com_keymagic_KeyMagicEngine
 * Method:    setKeyStates
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_keymagic_KeyMagicEngine_setKeyStates
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_keymagic_KeyMagicEngine
 * Method:    processKeyEvent
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_com_keymagic_KeyMagicEngine_processKeyEvent
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_keymagic_KeyMagicEngine
 * Method:    reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_keymagic_KeyMagicEngine_reset
  (JNIEnv *, jobject);

/*
 * Class:     com_keymagic_KeyMagicEngine
 * Method:    getContextText
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_keymagic_KeyMagicEngine_getContextText
  (JNIEnv *, jobject);

/*
 * Class:     com_keymagic_KeyMagicEngine
 * Method:    getDifference
 * Signature: (Ljava/lang/String;Ljava/lang/StringBuffer;)J
 */
JNIEXPORT jlong JNICALL Java_com_keymagic_KeyMagicEngine_getDifference
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_keymagic_KeyMagicEngine
 * Method:    setHistory
 * Signature: ([Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_keymagic_KeyMagicEngine_setHistory
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_keymagic_KeyMagicEngine
 * Method:    getHistory
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_keymagic_KeyMagicEngine_getHistory
  (JNIEnv *, jobject);

/*
 * Class:     com_keymagic_KeyMagicEngine
 * Method:    getSwitchMap
 * Signature: ()Ljava/util/HashMap;
 */
JNIEXPORT jobject JNICALL Java_com_keymagic_KeyMagicEngine_getSwitchMap
  (JNIEnv *, jobject);

/*
 * Class:     com_keymagic_KeyMagicEngine
 * Method:    setSwitchMap
 * Signature: (Ljava/util/HashMap;)V
 */
JNIEXPORT void JNICALL Java_com_keymagic_KeyMagicEngine_setSwitchMap
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
