#!/bin/bash
IMDir="Library/Input Methods"
# check if we are installing at for all users or current user
if [ -f "/$IMDir/kbLayouts.zip" ]
then # all users
	SRC_DIR="/$IMDir"
elif [ -f "$HOME/$IMDir/kbLayouts.zip" ]
then # current
	SRC_DIR="$HOME/$IMDir"
fi

# remove old keyboards
rm -rf "$HOME/.keymagic"
# remake dir
mkdir -p "$HOME/.keymagic"
# cd to dir
cd "$HOME/.keymagic/"
# move zip
mv "$SRC_DIR/kbLayouts.zip" "$HOME/.keymagic/"
# unzip
unzip -o "kbLayouts.zip"
# remove
rm "kbLayouts.zip"

exit 0