#!/bin/bash

# check if was installed to root or user home
if [ -f "/kbLayouts.zip" ]
then
	DESC_DIR="/"
elif [ -f "$HOME/kbLayouts.zip" ]
then
	DESC_DIR="$HOME/"
fi

# remove old keyboards
rm -rf "$HOME/.keymagic"
# remake dir
mkdir -p "$HOME/.keymagic"
# cd to dir
cd "$HOME/.keymagic/"
# move zip
mv "$DESC_DIR/kbLayouts.zip" "$HOME/.keymagic/"
# unzip
unzip -o "kbLayouts.zip"
# remove
rm "kbLayouts.zip"

exit 0